//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int ID { get; set; }
        public string Emp_Name { get; set; }
        public string Emp_ID { get; set; }
        public Nullable<int> Gender_ID { get; set; }
        public Nullable<System.DateTime> Emp_BirthDay { get; set; }
        public string Emp_Phone { get; set; }
        public Nullable<decimal> Emp_Salary { get; set; }
    
        public virtual Gender Gender { get; set; }
    }
}
